frr defaults traditional
hostname dc01leaf03
log syslog
log file /etc/frr/logs/dc01leaf03.log
log record-priority
log timestamp precision 3
no log unique-id
no ipv6 forwarding
!
debug zebra vxlan
debug ospf event
debug bgp neighbor-events
debug bgp updates in
debug bgp updates out
!
vrf TenantA
 vni 1000
exit-vrf
!
interface br10
 description vni10_bridge_domain (Anycast SVI for VLAN10/VNI10)
 ip address 10.10.1.1/24
exit
!
interface br20
 description vni20_bridge_domain (Anycast SVI for VLAN20/VNI20)
 ip address 10.10.2.1/24
exit
!
interface eth1
 description to_dc01spine01
 ip address 172.16.1.5/31
 ip ospf network point-to-point
exit
!
interface eth2
 description to_dc01spine02
 ip address 172.16.1.11/31
 ip ospf network point-to-point
exit
!
interface eth3
 description to_client3 (VLAN 10)
exit
!
interface eth4
 description to_client2 (VLAN 20)
exit
!
interface lo
 ip address 172.29.1.5/32
 ip ospf passive
exit
!
interface lo1
 description VTEP
 ip address 172.30.1.5/32
 ip ospf passive
exit
!
router bgp 65000
 bgp router-id 172.29.1.5
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 neighbor OVERLAY peer-group
 neighbor OVERLAY remote-as internal
 neighbor OVERLAY update-source lo
 neighbor 172.29.1.1 peer-group OVERLAY
 neighbor 172.29.1.1 description dc01spine01
 neighbor 172.29.1.2 peer-group OVERLAY
 neighbor 172.29.1.2 description dc01spine02
 !
 address-family l2vpn evpn
  neighbor OVERLAY activate
  advertise-all-vni
  vni 20
   rd 172.29.1.5:20
   route-target import 65999:20
   route-target export 65999:20
  exit-vni
  vni 10
   rd 172.29.1.5:10
   route-target import 65999:10
   route-target export 65999:10
  exit-vni
 exit-address-family
 !
 bmp targets GOBMP
  bmp monitor l2vpn evpn post-policy
  bmp monitor l2vpn evpn loc-rib
  bmp connect bmp-collector port 5000 min-retry 100 max-retry 720000 source-interface eth0
 exit
exit
!
router bgp 65000 vrf TenantA
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  advertise-pip
  rd 172.29.1.5:1000
  route-target import 65999:1000
  route-target export 65999:1000
 exit-address-family
exit
!
router ospf
 ospf router-id 172.29.1.5
 network 172.16.1.0/24 area 0.0.0.0
 network 172.29.1.5/32 area 0.0.0.0
 network 172.30.1.5/32 area 0.0.0.0
exit
!
end
