frr defaults traditional
hostname leaf03
log syslog
log file /etc/frr/logs/leaf03.log
log record-priority
log timestamp precision 3
no log unique-id
no ipv6 forwarding
!
ip prefix-list CONNECTED-LOOPBACKS seq 5 permit 172.29.1.5/32
ip prefix-list CONNECTED-LOOPBACKS seq 10 permit 172.30.1.5/32
!
route-map CONNECTED permit 10
 match ip address prefix-list CONNECTED-LOOPBACKS
exit
!
route-map PERMIT_ALL permit 10
exit
!
debug zebra vxlan
debug zebra evpn mh es
debug bgp neighbor-events
debug bgp updates in
debug bgp updates out
debug bgp evpn mh es
!
interface eth1
 description SPINE01
 ip address 172.31.1.9/31
exit
!
interface eth2
 description SPINE02
 ip address 172.31.1.11/31
exit
!
interface lo
 description Router ID
 ip address 172.29.1.5/32
exit
!
interface lo1
 description VTEP source
 ip address 172.30.1.5/32
exit
!
router bgp 65004
 bgp router-id 172.29.1.5
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 neighbor OVERLAY peer-group
 neighbor OVERLAY ebgp-multihop 2
 neighbor OVERLAY update-source lo
 neighbor OVERLAY capability extended-nexthop
 neighbor UNDERLAY peer-group
 neighbor 172.29.1.1 remote-as 65000
 neighbor 172.29.1.1 peer-group OVERLAY
 neighbor 172.29.1.2 remote-as 65001
 neighbor 172.29.1.2 peer-group OVERLAY
 neighbor 172.31.1.8 remote-as 65000
 neighbor 172.31.1.8 peer-group UNDERLAY
 neighbor 172.31.1.10 remote-as 65001
 neighbor 172.31.1.10 peer-group UNDERLAY
 !
 address-family ipv4 unicast
  redistribute connected route-map CONNECTED
  neighbor UNDERLAY activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor OVERLAY activate
  advertise-all-vni
  vni 10
   rd 172.29.1.5:10
   route-target import 65999:10
   route-target export 65999:10
  exit-vni
  !
  vni 20
   rd 172.29.1.5:20
   route-target import 65999:20
   route-target export 65999:20
  exit-vni
 exit-address-family
exit
!
end