apiVersion: 1

deleteDatasources:
  # - name: Prometheus
  #   orgId: 1
  - name: Loki
    orgId: 1
  - name: ClickHouse
    orgId: 1

datasources:
  # - name: Prometheus
  #   type: prometheus
  #   access: proxy
  #   orgId: 1
  #   url: http://prometheus:9090
  #   password:
  #   user:
  #   database:
  #   basicAuth: false
  #   basicAuthUser:
  #   basicAuthPassword:
  #   withCredentials:
  #   jsonData:
  #     graphiteVersion: "1.1"
  #     tlsAuth: false
  #     tlsAuthWithCACert: false
  #   secureJsonData:
  #     tlsCACert: "..."
  #     tlsClientCert: "..."
  #     tlsClientKey: "..."
  #   version: 1
  #   isDefault: true
  #   editable: true

  - name: Loki
    type: loki
    orgId: 1
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: bmp
      host: clickhouse
      port: 8123
      username: default
      protocol: http
      tlsSkipVerify: false
    secureJsonData:
      password:
