frr defaults traditional
hostname dc01fw01
log syslog
log file /etc/frr/logs/dc01fw01.log
log record-priority
log timestamp precision 3
no log unique-id
no ipv6 forwarding
!
ip prefix-list TENANTB-ALLOWED-FROM-A seq 5 permit 10.10.3.0/24
ip prefix-list TENANTA-ALLOWED-FROM-B seq 5 permit 10.10.1.0/24
ip prefix-list TENANTA-ALLOWED-FROM-B seq 10 permit 10.10.2.0/24
ip prefix-list DEFAULT-ONLY seq 5 permit 0.0.0.0/0
!
route-map TENANTA-IMPORT permit 10
 match ip address prefix-list TENANTB-ALLOWED-FROM-A
exit
!
route-map TENANTA-IMPORT permit 20
 match ip address prefix-list DEFAULT-ONLY
exit
!
route-map TENANTA-IMPORT deny 30
exit
!
route-map TENANTB-IMPORT permit 10
 match ip address prefix-list TENANTA-ALLOWED-FROM-B
exit
!
route-map TENANTB-IMPORT permit 20
 match ip address prefix-list DEFAULT-ONLY
exit
!
route-map TENANTB-IMPORT deny 30
exit
!
route-map TENANTA-OSPF-TO-BGP permit 10
 match ip address prefix-list TENANTA-ALLOWED-FROM-B
exit
!
route-map TENANTA-OSPF-TO-BGP deny 20
exit
!
route-map TENANTB-OSPF-TO-BGP permit 10
 match ip address prefix-list TENANTB-ALLOWED-FROM-A
exit
!
route-map TENANTB-OSPF-TO-BGP deny 20
exit
!
route-map TENANTA-BGP-TO-OSPF permit 10
 match ip address prefix-list TENANTB-ALLOWED-FROM-A
exit
!
route-map TENANTA-BGP-TO-OSPF deny 20
exit
!
route-map TENANTB-BGP-TO-OSPF permit 10
 match ip address prefix-list TENANTA-ALLOWED-FROM-B
exit
!
route-map TENANTB-BGP-TO-OSPF deny 20
exit
!
route-map FW-TO-PE1 permit 10
 match ip address prefix-list TENANTA-ALLOWED-FROM-B
exit
!
route-map FW-TO-PE1 permit 20
 match ip address prefix-list TENANTB-ALLOWED-FROM-A
exit
!
route-map FW-TO-PE1 deny 30
exit
!
route-map PE1-IN permit 10
 match ip address prefix-list DEFAULT-ONLY
exit
!
route-map PE1-IN deny 20
exit
!
route-map PERMIT_ALL permit 10
exit
!
debug zebra vxlan
debug ospf event
debug bgp neighbor-events
debug bgp updates in
debug bgp updates out
!
vrf TenantA
exit-vrf
!
vrf TenantB
exit-vrf
!
vrf Outside
exit-vrf
!
interface eth1
 description to_dc01border01_tenants
exit
!
interface eth1.1000
 description to_dc01border01_TenantA
 ip address 172.16.1.17/31
 ip ospf network point-to-point
exit
!
interface eth1.2000
 description to_dc01border01_TenantB
 ip address 172.16.1.19/31
 ip ospf network point-to-point
exit
!
interface eth2
 description to_pe1_internet
 ip address 10.100.1.10/30
exit
!
interface eth3
 description to_dc01border02_tenants
exit
!
interface eth3.1000
 description to_dc01border02_TenantA
 ip address 172.16.1.27/31
 ip ospf network point-to-point
exit
!
interface eth3.2000
 description to_dc01border02_TenantB
 ip address 172.16.1.29/31
 ip ospf network point-to-point
exit
!
interface lo
 ip address 172.29.1.8/32
exit
!
router bgp 65000 vrf TenantA
 !
 address-family ipv4 unicast
  redistribute ospf route-map TENANTA-OSPF-TO-BGP
  import vrf route-map TENANTA-IMPORT
  import vrf TenantB
  import vrf Outside
 exit-address-family
exit
!
router bgp 65000 vrf TenantB
 !
 address-family ipv4 unicast
  redistribute ospf route-map TENANTB-OSPF-TO-BGP
  import vrf route-map TENANTB-IMPORT
  import vrf TenantA
  import vrf Outside
 exit-address-family
exit
!
router bgp 65000 vrf Outside
 neighbor 10.100.1.9 remote-as 65010
 neighbor 10.100.1.9 description pe1
 !
 address-family ipv4 unicast
  neighbor 10.100.1.9 route-map PE1-IN in
  neighbor 10.100.1.9 route-map FW-TO-PE1 out
  import vrf TenantA
  import vrf TenantB
 exit-address-family
exit
!
router ospf vrf TenantA
 ospf router-id 11.11.11.11
 redistribute bgp route-map TENANTA-BGP-TO-OSPF
 network 172.16.1.16/31 area 0.0.0.0
 network 172.16.1.26/31 area 0.0.0.0
exit
!
router ospf vrf TenantB
 ospf router-id 22.22.22.22
 redistribute bgp route-map TENANTB-BGP-TO-OSPF
 network 172.16.1.18/31 area 0.0.0.0
 network 172.16.1.28/31 area 0.0.0.0
exit
!
end
