frr defaults traditional
hostname pe1
log syslog
log file /etc/frr/logs/pe1.log
log record-priority
log timestamp precision 3
no log unique-id
!
route-map PERMIT_ALL permit 10
exit
!
interface eth1
 description to_dc01fw01_internet
 ip address 10.100.1.9/30
exit
!
interface internet
 ip address 99.99.99.99/32
exit
!
router bgp 65010
 bgp router-id 172.16.0.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.100.1.10 remote-as 65000
 neighbor 10.100.1.10 description dc01fw01
 !
 address-family ipv4 unicast
  neighbor 10.100.1.10 activate
  neighbor 10.100.1.10 default-originate
 exit-address-family
exit
!
end
