frr defaults traditional
hostname dc01leaf02
log syslog
log file /etc/frr/logs/dc01leaf02.log
log record-priority
log timestamp precision 3
no log unique-id
no ipv6 forwarding
!
debug zebra vxlan
debug zebra evpn mh es
debug ospf event
debug bgp neighbor-events
debug bgp updates in
debug bgp updates out
debug bgp evpn mh es
!
vrf TenantA
 vni 1000
exit-vrf
!
vrf TenantB
 vni 2000
exit-vrf
!
interface br10
 description vni10_bridge_domain (Anycast SVI for VLAN10/VNI10)
 ip address 10.10.1.1/24
exit
!
interface br30
 description vni30_bridge_domain (Anycast SVI for VLAN30/VNI30)
 ip address 10.10.3.1/24
exit
!
interface eth1
 description to_dc01spine01
 evpn mh uplink
 ip address 172.16.1.3/31
 ip ospf network point-to-point
exit
!
interface eth2
 description to_dc01spine02
 evpn mh uplink
 ip address 172.16.1.9/31
 ip ospf network point-to-point
exit
!
interface eth3
 description to_client1
exit
!
interface eth4
 description to_client4
exit
!
interface lo
 ip address 172.29.1.4/32
 ip ospf passive
exit
!
interface lo1
 description VTEP
 ip address 172.30.1.4/32
 ip ospf passive
exit
!
interface mhbond1
 evpn mh es-df-pref 101
 evpn mh es-id 1
 evpn mh es-sys-mac aa:aa:39:00:00:01
exit
!
router bgp 65000
 bgp router-id 172.29.1.4
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 neighbor OVERLAY peer-group
 neighbor OVERLAY remote-as internal
 neighbor OVERLAY update-source lo
 neighbor 172.29.1.1 peer-group OVERLAY
 neighbor 172.29.1.1 description dc01spine01
 neighbor 172.29.1.2 peer-group OVERLAY
 neighbor 172.29.1.2 description dc01spine02
 !
 address-family l2vpn evpn
  neighbor OVERLAY activate
  advertise-all-vni
  vni 30
   rd 172.29.1.4:30
   route-target import 65999:30
   route-target export 65999:30
  exit-vni
  vni 10
   rd 172.29.1.4:10
   route-target import 65999:10
   route-target export 65999:10
  exit-vni
 exit-address-family
 !
 bmp targets GOBMP
  bmp monitor l2vpn evpn post-policy
  bmp monitor l2vpn evpn loc-rib
  bmp connect bmp-collector port 5000 min-retry 100 max-retry 720000 source-interface eth0
 exit
exit
!
router bgp 65000 vrf TenantA
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  advertise-pip
  rd 172.29.1.4:1000
  route-target import 65999:1000
  route-target export 65999:1000
 exit-address-family
exit
!
router bgp 65000 vrf TenantB
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  advertise-pip
  rd 172.29.1.4:2000
  route-target import 65999:2000
  route-target export 65999:2000
 exit-address-family
exit
!
router ospf
 ospf router-id 172.29.1.4
 network 172.16.1.0/24 area 0.0.0.0
 network 172.29.1.4/32 area 0.0.0.0
 network 172.30.1.4/32 area 0.0.0.0
exit
!
end
